controllers/nugus_controller/nugus_controller.cpp, controllers/nugus_controller/nugus_controller_test.cpp
The webots repo uses network endian for sending the size of the messages. I've changed it to network endian on (my pr)[https://github.com/NUbots/NUbots/pull/394] so I suppose it should be changed here also.
=> Changed the endian that we send to network endian

protos/NUgus.proto
Robot Model Specifications, under "structure of the robot", need to annotate body parts with suffixes, hence "right shoulder pitch" becomes "right shoulder pitch [shoulder]"
=> Change syntax to match NUbots requirements

CMakeLists.txt
Address sanitizer and undefined behaviour sanitizer can be useful in finding and debugging buggy code.
This PR adds options to the cmake configuration to enable them.
I have tested these by using `ldd` on `nugus_controller`, and `ldd` reports that `nugus_controller` is linked to the sanitizers if they are enabled.
=> Adds ASan and UBSan as build options

.gitignore
Converting a NUgus to base nodes in webots generates `worlds/NUgus_textures` and `worlds/robot`, which we don't want to commit.
=> Ignore files webots generates when converting a NUgus to base nodes

.gitignore, protos/robot/NUgus.proto
The textures seem to work fine in our worlds, but the ones in the separate mesh proto files can't find the textures when running the RoboCup controller because the `robots` folder doesn't exist. This changes them from being relative to the proto to relative to its own location (mesh folder).
=> Fixes the textures inside mesh files for the RoboCup controller

controllers/teleport_master_controller/teleport_master_controller.cpp, worlds/vision_collection.wbt
Sets the ball height to its own height so it doesn't float, and adds the ball to the master teleport controller args. 
Set the lil Darwin to its own height as well because it was floating.
=> Set the height based on model name

protos/robot/NUgus.proto
Currently it is `void`, which means in the official RoboCup setup, the robot loads the void controller. It should by default try to load the player controller.
=> Change the default controller of the NUgus robot

protos/robot/NUgus.proto
Looks like they were missed when adding them in initially.
=> Add in missing MX64-vel and MX106-vel in maxVelocity of motors

worlds/kid.wbt
The height that the robot is dropped into the world is problematic for running our code on. It gives a negative z acceleration which makes the robot immediately get up. This height change works ok, with no get up triggered. This is also the height as defined in our team config for RoboCup.
=> Change the robot height in kid.wbt

protos/robot/NUgus.proto
We didn't have any center of mass so the automatic marking tool gave us warnings. This PR fixes this so we have a COM on the touch sensors. It's put to [0 0 0] because they are so small the actual position shouldn't be an issue.
=> Adds center of mass to physics node of touch sensors

protos/robot/NUgus.proto
This PR reduces the radius of the cylinder bounding box.
=> Reduce hip cylinder radius

protos/robot/NUgus.proto
A requirement for playing with our robot in RoboCup 2021. Moves bounding objects on feet so they don't touch the cleats. Puts capsule bounding boxes on touch sensors that cover the cleats.
=> Change to using capsules for the bounding box for the cleats

protos/robot/NUgus/postures.json
Doesn't pass the auto model checking otherwise. Somehow this slipped through the cracks when updating this repo post-RoboCup.
=> Updates the postures.json so that the NUgus arms by its side in the upright posture

protos/robot/NUgus/NUgus.proto, protos/robot/NUgus/NUgus_mesh/NUgusMain.proto, protos/robot/NUgus/NUgus_mesh/NUgus_headMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_left_ankleMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_left_footMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_left_hip_rollMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_left_hip_yawMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_left_lower_armMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_left_lower_legMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_left_shoulderMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_left_upper_armMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_left_upper_legMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_neckMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_right_ankleMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_right_footMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_right_hip_rollMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_right_hip_yawMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_right_lower_armMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_right_lower_legMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_right_shoulderMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_right_upper_armMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_right_upper_legMesh.proto, protos/robot/NUgus/NUgus_mesh/NUgus_torsoMesh.proto, worlds/vision_collection.wbt
It was relative to the protos folder rather than the proto itself. This caused issues in the RoboCup world because the location of the proto there was in the first level of the protos folder, whereas in our proto folder it's under a robot folder.
This PR changes it so the textures are relative to the main proto, `NUgus.proto`.
=> Fix the NUgus robot's texture path

scripts/format.py
`./b format` currently tries formatting all files in NUWebots, including those in `NUWebots/webots/`. This folder isn't our code, it's a submodule containing the Webots simulator code. We don't want to format files in this folder.
This PR updates the format script so it only formats our files and ignores the `webots` folder.
=> Removes the webots folder from formatting

worlds/kid.wbt
Super small PR but this has been annoying me a lot. There's no reason for other robots in the kid world, they don't do anything but increase the complexity and clutter the console with warnings. This PR removes them, leaving just our nugus_controller controlled blue NUgus.
=> Remove other robots in our kid world

nuwebots/controllers/nugus_controller/CMakeLists.txt, nuwebots/controllers/nugus_controller/nugus_controller.cpp, nuwebots/shared/message/messages.proto, nuwebots/worlds/kid.wbt
- Adds message to support goal detection benchmarking using groundtruth data from webots.
https://github.com/NUbots/NUbots/pull/988/
=> Add live Webots vision error testing (goal detection) 

worlds/kid.wbt
When using RoboCup, the first red robot is on port 10001. In the kid world, we've had 10020 as the port. This is really annoying because we have to keep switching. This PR standardises it so it's using 10001. 
Goes with NUbots/NUbots#1086.
=> Use port 10001 by default in Kid world, to standardise with RoboCup 

controllers/nugus_controller/nugus_controller.cpp
This PR does the following:
- Renames space `x` to `f` to avoid confusion, field space is the webots absolute frame so makes sense to just call it `f` rather then `x`
- Updates initialization of `Hfw` to allow robot to start in any orientation
=> Fix up naming conventions of the various spaces and initialisation of Hfw

CMakeLists.txt
This has been sitting like this for ages and it causes compilation to fail for people setting it up for the first time. Might as well turn it off at this point.
=> Turn off clang tidy by default

controllers/nugus_controller/nugus_controller.cpp
This PR reduces camera FPS in webots to 25 FPS to match current real hardware settings, this is to help reduce any sim2real gap related to camera frame rate when developing algorithms reliant on images. https://github.com/NUbots/NUbots/pull/1571
=> Reduce webots camera fps
